-- # SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
-- # FROM ANIMAL_OUTS
-- # LEFT JOIN ANIMAL_INS
-- # ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID

-- # SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
-- # FROM ANIMAL_OUTS
-- # LEFT JOIN ANIMAL_INS
-- # ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
-- # HAVING ANIAML_OUTS.DATETIME < ANIMAL_INS.DATETIME;

-- # 거의 답에 근접한듯?
-- # SELECT * 
-- # FROM ANIMAL_OUTS
-- # LEFT JOIN ANIMAL_INS
-- # ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
-- # WHERE ANIMAL_OUTS.DATETIME < ANIMAL_INS.DATETIME;

-- # 이거 왜 답 아니냐;;;
-- # SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
-- # FROM ANIMAL_OUTS
-- # LEFT JOIN ANIMAL_INS
-- # ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
-- # WHERE ANIMAL_OUTS.DATETIME < ANIMAL_INS.DATETIME
-- # ORDER BY ANIMAL_INS.DATETIME ASC;


SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
FROM ANIMAL_INS
LEFT JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_OUTS.DATETIME < ANIMAL_INS.DATETIME
ORDER BY ANIMAL_INS.DATETIME ASC;