-- # SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE AS '중성화'
-- # FROM ANIMAL_INS
-- # WHERE SEX_UPON_INTAKE LIKE '%ed%'
-- # ORDER BY ANIMAL_ID ASC;

SELECT ANIMAL_ID, NAME,
CASE 
WHEN SEX_UPON_INTAKE LIKE '%ed%' THEN 'O'
ELSE 'X'
END AS '중성화'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID ASC;